apiVersion: v1
kind: Service
metadata:
  name: myapp1-svc
spec:
  type: ClusterIP
  selector:
    app: myapp
    version: v1
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1-deploy
  labels:
    app: myapp
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: v1
  template:
    metadata:
      labels:
        app: myapp
        version: v1
    spec:
      containers:
      - name: myappv1
        image: stackupiss/northwind-app:v1
        imagePullPolicy: Always
        env:
          - name: DB_HOST
            value: mydb-svc.default.svc.cluster.local
          - name: DB_PASSWORD
            value: changeit
          - name: DB_USER
            value: root
          - name: DB_PORT
            value: "3306"
        ports:
          - containerPort: 3000