version: '3' 

volumes: 
  nwvol: 

networks: 
  nwnet:

services:
  nwdb:
    image: wynnt3o/nwdb:v1
    build: 
      context: ./database
    environment:
    - MYSQL_ROOT_PASSWORD=changeit
    - MYSQL_DATABASE=northwind
    networks:
    - nwnet
    volumes:
    - nwvol:/var/lib/mysql

  nwapp:
    image: wynnt3o/nwapp:v1
    build:
      context: ./server
    environment:
    - DB_HOST=nwdb
    - DB_PORT=3306
    - DB_USER=root
    - DB_PASSWORD=changeit
    networks:
    - nwnet
    ports:
    - 80:3000
  

  
